[package]
name = "paraforge"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
serde = { version = "1.0.189", features = ["derive"] }
serde_json = "1.0.107"
serde_tuple = "0.5.0"
serde_repr = "0.1.17"
base64 = "0.21.5"
nalgebra = "0.32.4"
